// OneSignal Removed

import { cleanupOutdatedCaches, precacheAndRoute } from 'workbox-precaching'
import { clientsClaim } from 'workbox-core'

self.skipWaiting()
clientsClaim()

// Precache all assets generated by vite
cleanupOutdatedCaches()
precacheAndRoute(self.__WB_MANIFEST)

// Handle skipWaiting message
self.addEventListener('message', (event) => {
    if (event.data && event.data.type === 'SKIP_WAITING') {
        self.skipWaiting()
    }
})

// Handle Notification Click
self.addEventListener('notificationclick', (event) => {
    event.notification.close()

    const urlToOpen = event.notification.data?.url

    if (!urlToOpen) return

    event.waitUntil(
        clients.matchAll({
            type: 'window',
            includeUncontrolled: true
        }).then((windowClients) => {
            // Check if there is already a window/tab open with the target URL
            // Or just any window of our app that we can focus and navigate
            for (let client of windowClients) {
                // If we find a client that is already open, focus it
                if (client.url.includes(self.registration.scope) && 'focus' in client) {
                    return client.focus().then(focusedClient => {
                        // Navigate the focused client to the target URL
                        return focusedClient.navigate(urlToOpen)
                    })
                }
            }

            // If no window is open, open a new one
            if (clients.openWindow) {
                return clients.openWindow(urlToOpen)
            }
        })
    )
})
